apply plugin: "java"
apply plugin: "maven-publish"
apply plugin: "checkstyle"

java {
    withSourcesJar()
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
}

repositories {
    mavenCentral()
}

dependencies {
    implementation "com.google.code.gson:gson:2.8.6"
    testImplementation "org.junit.jupiter:junit-jupiter:5.9.1"
    testImplementation "org.nanohttpd:nanohttpd-websocket:2.3.1"
}

test {
    useJUnitPlatform()
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java

            groupId = 'com.github.william27b'
            artifactId = 'ftc-dashboard'
            version = 'pesto-dashboard'

            pom {
                description = "Web dashboard designed for FTC"
                name = "FTC Dashboard"
                url = "https://github.com/william27b/ftc-dashboard"

                // TODO: remove this license
                licenses {
                    license {
                        name = "The MIT License"
                        url = "https://opensource.org/licenses/MIT"
                        distribution = "repo"
                    }
                }

                developers {
                    developer {
                        id = "william27b"
                        name = "William"
                        email = "your@email.com"
                    }
                }

                scm {
                    url = "https://github.com/william27b/ftc-dashboard"
                }
            }
        }
    }
}